###
GET http://localhost:5000/api/pedidos?page=1&limit=10 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7Im5vbWJyZSI6IkRpZWdvIn0sImlhdCI6MTcwMDI3ODkyNywiZXhwIjoxNzAwMjgyNTI3fQ.FvRpoXoOXOEFV-PuHsalHAkKCnvXyMMVCK4d7DzdeEQ

###
POST http://localhost:5000/api/pedidos HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7Im5vbWJyZSI6IkRpZWdvIn0sImlhdCI6MTcwMDI3ODkyNywiZXhwIjoxNzAwMjgyNTI3fQ.FvRpoXoOXOEFV-PuHsalHAkKCnvXyMMVCK4d7DzdeEQ

{
        "id_usuario": "2f9207f9-86fb-49fe-b98c-83a80ee822b0",
        "id_producto": "18806413-aab9-4a91-93f3-3378b55b5e25",
        "nombre_pedido": "Tulipanes rojos",
        "cantidad": 2,
        "especificacion": "Que se vea bonito",
        "dedicatoria": "I love you",
        "status": true
}


###
GET http://localhost:5000/api/pedidos/pedido/308d25e3-a877-425b-a9e7-0bb3c471552a HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7Im5vbWJyZSI6IkRpZWdvIn0sImlhdCI6MTcwMDI3ODkyNywiZXhwIjoxNzAwMjgyNTI3fQ.FvRpoXoOXOEFV-PuHsalHAkKCnvXyMMVCK4d7DzdeEQ

###
DELETE http://localhost:5000/api/pedidos/eliminarFisico/0f8ca9a3-427b-4472-ab4f-5e6222c0adc2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7Im5vbWJyZSI6IkRpZWdvIn0sImlhdCI6MTY5OTkwNjY0OCwiZXhwIjoxNjk5OTEwMjQ4fQ.YZYdihyosCn_nZBmjL5_Qt1XtX1tlrgf9U0HbfOb9q8
###
DELETE http://localhost:5000/api/pedidos/eliminarLogico/0f8ca9a3-427b-4472-ab4f-5e6222c0adc2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoyNX0sImlhdCI6MTY5OTEyMjg0NiwiZXhwIjoxNjk5MTI2NDQ2fQ.a-TpxC4pUe52441wB675rJpa1aZl7viwrHxs-P7LlIc

###
PUT http://localhost:5000/api/pedidos/actualizarCompleto/3f78dd14-ceda-4a3e-963c-02f3f8351c77 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7Im5vbWJyZSI6IkRpZWdvIn0sImlhdCI6MTY5OTkwNTU0MywiZXhwIjoxNjk5OTA5MTQzfQ.uME_vh4j8noZhK4Na-R2LC4Hye_Ui3usV8EZ0uryJ2w

{
    "nombre": "fresas",
    "cantidad": 10,
    "especificacion": "Que se vea más bonito",
    "dedicatoria": "TQM"
}


###
PATCH http://localhost:5000/api/pedidos/actualizarParcial/3f78dd14-ceda-4a3e-963c-02f3f8351c77 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7Im5vbWJyZSI6IkRpZWdvIn0sImlhdCI6MTY5OTkwNzEzOSwiZXhwIjoxNjk5OTEwNzM5fQ.t-cHFGBWjIZp3tH7OEmg0-9h_wgAgHwZoTMDbIStL7g

{
    "nombre": "fresitas"
}

###
GET http://localhost:5000/api/pedidos/pedidosUser/a0877488-3b4e-4e4d-aadb-1334a5be2829 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7Im5vbWJyZSI6IkRpZWdvIn0sImlhdCI6MTY5OTkwNzEzOSwiZXhwIjoxNjk5OTEwNzM5fQ.t-cHFGBWjIZp3tH7OEmg0-9h_wgAgHwZoTMDbIStL7g

###
GET http://localhost:5000/api/pedidos/pedidosPendientes HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7Im5vbWJyZSI6IkRpZWdvIn0sImlhdCI6MTY5OTkwNzEzOSwiZXhwIjoxNjk5OTEwNzM5fQ.t-cHFGBWjIZp3tH7OEmg0-9h_wgAgHwZoTMDbIStL7g