DELETE http://localhost:5000/api/productos/deleteFisico/259e42cb-ecc2-4a34-8929-0ef372ff4820 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNGQ4Yjk5NjAtNzkxMS00OGNlLWE1NGMtZjBiNjNmZWQ4NDZjIiwibm9tYnJlIjoiZmVybmFuZG8ifSwiaWF0IjoxNzAxMzEzMzk2LCJleHAiOjE3MDEzMTY5OTZ9.9p3asWHbpwiLjRQz0Sm3QojzOHpQkQsbR06wwRY8tEs
