DELETE http://localhost:5000/api/productos/deleteFisico/9ca14181-5647-4b6b-a808-ec2072140970 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7Im5vbWJyZSI6IkRpZWdvIn0sImlhdCI6MTY5OTkyMTAwNSwiZXhwIjoxNjk5OTI0NjA1fQ.g3CVRbTmG1oPS1eS29XnlM-cWSmea_LimMvtXBSSR8w
