###
DELETE http://localhost:5000/api/productos/deleteFisico/3288e2a7-e9b0-4aff-a200-feb850b5d374 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiMDI2YWE0ODktMmQ4ZS00MmIzLWJjM2UtNjA3NzEyOGVjMDZiIiwibm9tYnJlIjoiZmVybmFuZG8ifSwiaWF0IjoxNzAxMzU4OTk5LCJleHAiOjE3MDEzNjI1OTl9.sGBRCB_PA0avXnkDCq9opl_FUnSp9xXNPk3g3VE8YNE