###
PUT http://localhost:5000/api/productos/update/9ca14181-5647-4b6b-a808-ec2072140970 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7Im5vbWJyZSI6IkRpZWdvIn0sImlhdCI6MTY5OTkyMjEwOCwiZXhwIjoxNjk5OTI1NzA4fQ.epmpNvkGWCGhtj0NEBIWuYyQpxh0AyiCbUbaCqHHWkg

{
    "nombre_producto": "ROSALES",
    "precio": 50,
    "id_tamaño": 3,
    "tipo_producto": 1
}

###
PATCH http://localhost:5000/api/productos/parcialUpdate/c11dcba4-6067-4ad9-b742-6e31af1690d7 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7Im5vbWJyZSI6IkRpZWdvIn0sImlhdCI6MTY5OTkyMTAwNSwiZXhwIjoxNjk5OTI0NjA1fQ.g3CVRbTmG1oPS1eS29XnlM-cWSmea_LimMvtXBSSR8w

{
  "nombre_producto": "ositos de fresas"
}
