###
GET http://localhost:5000/api/entregas/entregasAprobadas/sinFecha HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiZGU0MmM3NDAtNDQ3YS00MTczLThjZWItN2MzNTE0YzU3ODIyIiwibm9tYnJlIjoiZmVybmFuZG8ifSwiaWF0IjoxNzAwNjY1NTUwLCJleHAiOjE3MDA2NjkxNTB9.xwb54PLJEexJhcFXwStOXAFVqyVtbX55ZxPuGURpEFg