###
GET http://localhost:5000/api/entregas/0d76581c-6924-470a-a851-1f049836a91c HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7Im5vbWJyZSI6IkRpZWdvIn0sImlhdCI6MTcwMDM0MjE5NywiZXhwIjoxNzAwMzQ1Nzk3fQ.fE3wcnNcdNpODYlmeOIv6L91FVOGKkDty5kEr9rEq8I