GET http://localhost:5000/api/entregas/entregasAprobadas/sinFecha HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiMmY5MjA3ZjktODZmYi00OWZlLWI5OGMtODNhODBlZTgyMmIwIiwibm9tYnJlIjoiRGllZ28ifSwiaWF0IjoxNzAwNDI0NTYyLCJleHAiOjE3MDA0MjgxNjJ9.vVVH9NnCQ8_V3XC5GK4e-TZXGLKq3-qn7THyVzS6im8