###
GET http://localhost:5000/api/entregas/070c44e6-a348-4f85-9fb5-bffab836e1a8 HTTP/1.1

Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiZGU0MmM3NDAtNDQ3YS00MTczLThjZWItN2MzNTE0YzU3ODIyIiwibm9tYnJlIjoiZmVybmFuZG8ifSwiaWF0IjoxNzAwNjcwMDQzLCJleHAiOjE3MDA2NzM2NDN9.0aqjT_Kc5t6d5ZeTU8ljX46Ww9xsBJ2Y-gsAkOcTXNY