###
GET http://localhost:5000/api/entregas?page=1&limit=10 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiM2Y1YTE4YTktYmFjYS00NDlhLWFjMDctMGM1MGQwNWM4MWI1Iiwibm9tYnJlIjoiMTIzIn0sImlhdCI6MTcwMDQzNjAzMiwiZXhwIjoxNzAwNDM5NjMyfQ.c_3eUxfv180bWL-j6H1p881muDuiS3dMO7EAo3CsUZk