###
POST http://localhost:5000/api/entregas HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiMDI2YWE0ODktMmQ4ZS00MmIzLWJjM2UtNjA3NzEyOGVjMDZiIiwibm9tYnJlIjoiZmVybmFuZG8ifSwiaWF0IjoxNzAxMzI1ODQzLCJleHAiOjE3MDEzMjk0NDN9.FEzsO-ufDJcBLUOLefp4tTpiOXtb-8mH3XI0-cC6LYA

{
    "id_pedido": "ebe0f318-f17a-4532-95a9-00959d7988d0",
    "lugar": "calle tepeaca",
    "horario": "13:45:00",
    "fecha": null,
    "total": 250
}