DELETE http://localhost:5000/api/usuarios/fisico/33 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoyNX0sImlhdCI6MTY5OTM3MTc3NiwiZXhwIjoxNjk5Mzc1Mzc2fQ.8_ULtXn8D93xTLntlA0wY1kVRbbHLVt04nBn-wSZyAo