DELETE http://localhost:5000/api/usuarios/fisico/d26b16e8-93af-470c-8ab1-fd3cc69907fe HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7Im5vbWJyZSI6IkRpZWdvIn0sImlhdCI6MTY5OTc1NTUzOCwiZXhwIjoxNjk5NzU5MTM4fQ.WflD0WwGDI9jENP3W_bkqCJVCiIQPkan-CnIn-aRo50