###
GET http://localhost:5000/api/usuarios/d26b16e8-93af-470c-8ab1-fd3cc69907fe HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7Im5vbWJyZSI6IkRpZWdvIn0sImlhdCI6MTY5OTc1NDI4OCwiZXhwIjoxNjk5NzU3ODg4fQ.yPEwz-O0iH9Hws9BoKoUDdlHrK-bZAlFdsO-soTEWlA