###
POST http://localhost:5000/api/usuarios HTTP/1.1
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7Im5vbWJyZSI6IkRpZWdvIn0sImlhdCI6MTY5OTkwMzEwNywiZXhwIjoxNjk5OTA2NzA3fQ.OD1lYt5DyVZ9a7WhOv5Mj_KvRe9THDRl6PvA_lv6N04

{
    "nombre": "Kenay",
    "apellido" : "Urbina",
    "telefono": "9611727213",
    "email": "email1@gmail.com",
    "password": "1234",
    "tipo": 1
}