###
PUT http://localhost:5000/api/productos/update/0addcb6c-513a-4cc9-9fa8-14eec61425d0 HTTP/1.1
Content-Type: application/json
{
    "Prod_Name": "Producto 15",
    "Price": 29,
    "Width": 10,
    "Height": 20,
    "Colour": "Red",
    "Images": "https://example.com/product1.jpg",
    "state_delete": "N",
    "Delete_at": null,
    "Created_at": null,
    "Update_at": null
}